on:
  workflow_dispatch:
    # inputs:
    #   branch:
    #     description: 'Branch to run the workflow on'
    #     required: true

jobs: 
  checkout:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

  call-workflow:
    uses: ./.github/workflows/show_branch.yml

  send-message-to-slack:
    runs-on: macos-latest
    steps:
      - name: send message to slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Finished!"}' https://hooks.slack.com/services/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
    
