on:
  workflow_dispatch:
    # inputs:
    #   branch:
    #     description: 'Branch to run the workflow on'
    #     required: true

jobs: 
  checkout:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

  call-workflow:
    uses: ./.github/workflows/show_branch.yml
    
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
