name: Show branch

on:
  workflow_call:

jobs:
  show_branch:
    runs-on: [macos-latest]
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
